["general"]
mixins = ["~/.co.toml", "co:npm"]

["test"]
commands = ["test"]
scripts = ["read  name && echo \"hello $name,welcome to my program\""]

["where is tsc"]
commands = ["where-is-tsc", "wt"]
scripts = ["echo tsc in: <%= loadNodeModuleBin('typescript', 'tsc') %>"]

["start"]
commands = ["dev", "start"]
scripts = [
    # the command to run, can run multiple
    'node ./bootstrap.js',
]

["build"]
commands = ["build"]
scripts = [
    #
    'rm -rf ./dist',
    'pkg . --targets node18-linux-x64 --compress Brotli',
    'cp ./package/package.json.template ./dist/package.json && cp ./README.md ./dist/README.md',
    'echo "\"bin\": {\"co\": \"co\"}," >>  ./dist/package.json',
    'echo "\"name\": \"co-linux-x64\"" >> ./dist/package.json  && echo "}" >> ./dist/package.json',
    'cd ./dist && npm publish --access public',
    #
    'rm -rf ./dist',
    'pkg . --targets node18-linux-arm64 --compress Brotli',
    'cp ./package/package.json.template ./dist/package.json && cp ./README.md ./dist/README.md',
    'echo "\"bin\": {\"co\": \"co\"}," >>  ./dist/package.json',
    'echo "\"name\": \"co-linux-arm64\"" >> ./dist/package.json  && echo "}" >> ./dist/package.json',
    'cd ./dist && npm publish --access public',
    #
    'rm -rf ./dist',
    'pkg . --targets node18-macos-x64 --compress Brotli',
    'cp ./package/package.json.template ./dist/package.json && cp ./README.md ./dist/README.md',
    'echo "\"bin\": {\"co\": \"co\"}," >>  ./dist/package.json',
    'echo "\"name\": \"co-macos-x64\"" >> ./dist/package.json  && echo "}" >> ./dist/package.json',
    'cd ./dist && npm publish --access public',
    #
    'rm -rf ./dist',
    'pkg . --targets node18-macos-arm64 --compress Brotli',
    'cp ./package/package.json.template ./dist/package.json && cp ./README.md ./dist/README.md',
    'echo "\"bin\": {\"co\": \"co\"}," >>  ./dist/package.json',
    'echo "\"name\": \"co-macos-arm64\"" >> ./dist/package.json  && echo "}" >> ./dist/package.json',
    'cd ./dist && npm publish --access public',
    #
    'rm -rf ./dist',
    'pkg . --targets node18-win-x64 --compress Brotli',
    'cp ./package/package.json.template ./dist/package.json && cp ./README.md ./dist/README.md',
    'echo "\"bin\": {\"co\": \"co.exe\"}," >>  ./dist/package.json',
    'echo "\"name\": \"co-win-x64\"" >> ./dist/package.json  && echo "}" >> ./dist/package.json',
    'cd ./dist && npm publish --access public',
]

["linux-install-ldid"]
commands = ["lil"]
scripts = [
    # the command to run, can run multiple
    'cd /bin && wget https://github.com/ProcursusTeam/ldid/releases/download/v2.1.5-procursus7/ldid_linux_x86_64 && mv /bin/ldid_linux_x86_64 /bin/ldid && chmod +x /bin/ldid',
]
