["general"]
mixins = ["~/.co.toml", "co:yarn"]

["say"]
commands = ["say", "speak", "echo"]
scripts = [
    # the command to run, can run multiple
    "echo '<%= args || 'hello world' %>'",
    "echo '📜 try editing .co.toml'",
]
