["git:commit"]
commands = ["git:commit", "g:c"]
scripts = [
    # the command to run, can run multiple
    'git add --all',
    '''
    git commit -m <%= JSON.stringify(
        await ui({
            type: "input",
            message: 'Enter commit message',
            initial: 'update'
        })
    ) %>
    ''',
]

["git:publish"]
commands = ["git:publish", "g:p"]
scripts = [
    # the command to run, can run multiple
    'goto:git:commit',
    'git push',
]
