["install"]
commands = ["install", "i", "add", "a"]
scripts = [
    # the command to run, can run multiple
    '<% if (argsArr.length === 0) { %>npm install<% } else { %>npm install --save <%= args %><% } %>',
]

["install (dev)"]
commands = ["install:dev", "i:d", "add:dev", "a:d"]
scripts = [
    # the command to run, can run multiple
    'npm install --save-dev <%= args %>',
]

["install (global)"]
commands = ["install:global", "i:g", "add:global", "a:g"]
scripts = [
    # the command to run, can run multiple
    'npm install --global <%= args %>',
]

["update"]
commands = ["update", "up", "upgrade"]
scripts = [
    # the command to run, can run multiple
    'npm upgrade',
]

["uninstall"]
commands = ["uninstall", "un", "remove", "rm"]
scripts = [
    # the command to run, can run multiple
    'npm uninstall <%= args %>',
]

["run"]
commands = ["run", "r"]
scripts = [
    # the command to run, can run multiple
    'npm run <%= args %>',
]

["execute"]
commands = ["execute", "x"]
scripts = [
    # the command to run, can run multiple
    'npx <%= args %>',
]
